version: '3.4'
services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: build
    command: yarn start:dev reservations
    volumes:
      - .:/app
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    env_file:
      - ./apps/reservations/.production.env
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: build
    command: yarn start:dev auth
    volumes:
      - .:/app
    ports:
      - '5001:5001'
    depends_on:
      - mongo
    env_file:
      - ./apps/auth/.production.env
  mongo:
    image: mongo:4.4.22
    ports:
      - '27017:27017'
